### ISSUE TITLE
Test syncing protected content

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#1009]
1. Add a repository from red hat CDN[0]
2. Sync repository.
3. Publish repository.
4. Download content from published repository. 

[0] https://docs.pulpproject.org/plugins/pulp_rpm/user-guide/recipes.html?#sync-a-protected-repo

**Comment by ragabala** [comment]
Hi @dkliban ,

Was able to test this manually. Here are the findings. I tried pulling content from the Redhat CDN[0]
in two machines simultaneously
1) giving the entitlement certificates
2) Without the entitlement certificates

I was able to get the content only in the case when the certificates were given. Also since the contents that are available in the protected repo are huge in numbers(21K rpms approx.), the sync crashed my local mongo. Hence, I had to pass the parameter download-policy=on_demand that just collected the manifest. This however took around 10 mins just for the content sync. Like we discussed, this was beyond the scope of automation , hence closing this one out.


[0] https://cdn.redhat.com/content/dist/rhel/server/6/6Server/x86_64/os
