### ISSUE TITLE
Test tasks purge

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#108]
Test that tasks can be listed and completed tasks can be purged.
https://pulp.plan.io/issues/1418

Steps
1. Perform a few repository operations
2. List all the tasks 
3. Purge completed tasks

The CLI commands for listing and purging tasks are
pulp-admin tasks list 
pulp-admin tasks list -a
pulp-admin tasks -s "waiting"

CLI commands
pulp-admin tasks purge -a 
pulp-admin tasks purge -s "successful"

**Comment by shubham90** [comment]
I would like to add that although 'canceled' state comes under completed states, but it cannot be purged.

**Comment by dkliban** [comment]
@shubham90 Why did we decide to not allow purging of canceled tasks?

**Comment by shubham90** [comment]
@dkliban because it is not necessary that the tasks which are tagged as 'canceled' are actually canceled because of the asynchronous call of cancel tasks function. It first puts the state as cancel and then asynchronously tries to cancel the task. So, there might be a possible situation where canceled state task is still not completed.

**Comment by dkliban** [comment]
@shubham90 makes sense. Thanks!
