### ISSUE TITLE
Reverse dockerhub feeds v1 and v2

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#123]
Apparently, Dockerhub switched their registries. index.docker.io is now v2 and registry-1.docker.io is v1.

https://pulp.plan.io/issues/1685

**Comment by Ichimonji10** [comment]
d93de79f0cec13779a719d45d3a8e4dac1cd34dd creates and uses two new constants, `DOCKER_V1_FEED_URL` and `DOCKER_V2_FEED_URL`. However, that commit does not swap the URLs for these two feeds. This is because, in my tests, swapping these URLs triggers new test failures.

Are we confident in [pulp issue 1685](https://pulp.plan.io/issues/1685)?

**Comment by Ichimonji10** [comment]
Unassigning from self, as I'm not actively working on this.

**Comment by asmacdo** [comment]
@Ichimonji10 after chatting with some docker devs, I think we can close pulp issue 1685. I don't think that pulp-smash needs to change anything, but index.docker.io (and all Docker v1 content for that matter) are deprecated and might be removed in the near term. We should leave as is for now so we know we work with v1 as long as they have it on.

**Comment by Ichimonji10** [comment]
Thanks for the heads up.
