### ISSUE TITLE
Discussion on Refactoring setup Global Repository in pulp-rpm Automation

### ISSUE THREAD

**Issue by danuzclaudes** [PulpQE/pulp-smash#330]
I find this [setUpModule()](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/cli/test_copy_units.py#L18) especially helpful to make pulp-rpm tests robust.

But I'd also like to propose, is it possible for me to **refactor creating and syncing a global repo** into `pulp-smash/pulp_smash/tests/rpm/utils.py` directly? The reason is that, multiple tests may require one and **only one repository**, including [this](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/cli/test_sync.py#L57) targeting on sync, as well as my pending or future PRs.

In that case, instead of declaring extra repo, this `_REPO_ID`, which has been globalized in `setUpModule()`, is enough for these test cases, right? If so, I'd like to contribute the change to all modules in pup-rpm tests before fixing further issues.

Btw, I think the Discussion label is very nice :  )

**Comment by Ichimonji10** [comment]
I want to suss out a detail here: Are you proposing that `setUpModule` itself be moved into a `utils` module? Or are you proposing that the logic for creating and syncing (and destroying) a repository be moved into a `utils` module, and then calling that logic from `test*` modules?

If your proposal is the former, then - maybe that'll work? I'm unsure of what unittest2 (and the other commonly used test runners, including unittest, nose and py.test) will do when they encounter a `setUpModule` function in a `utils` module. I think they'll ignore it, but I leave it as an exercise for you to figure out. Similarly, you could try moving the `setUpModule` function into somewhere like `pulp_smash/tests/rpm/test_fixtures.py`. Again, I'm not sure how the test runners will handle that.

If your proposal is the latter, then yes, that makes sense to me, and I'm pretty sure it can be done. Give it a shot.

**Comment by Ichimonji10** [comment]
There's a couple interesting questions to suss out, still. Setting this to "discussion".

**Comment by danuzclaudes** [comment]
The idea is creating a single repository, syncing data into it and then test on either langpacks, syncing, etc, with this "global" repository. It'll really speed up test execution time.

However, there are two ways to implement this idea:
(1) Module call approach: this has already been tried with [this branch](https://github.com/PulpQE/pulp-smash/compare/master...danuzclaudes:2.9-issue-setupmodule?expand=1).

Several different modules will call `create_sync_global_repo()` in their `setUpModule()` functions and `destroy_global_repo()` in `tearDownModule()`. "A truly global repository would be created just once before each of the tests in `pulp_smash/tests/rpm/cli/test*` modules are executed by the test runner." And then, when the modules are done being executed by the test runner, the global repository can be destroyed. But the question is, will  `python -m unittest2 discover pulp_smash.tests.rpm.cli` run all rpm.cli tests concurrently?

(2) Inheritance approach:

Create a `rpm.cli.BaseTestCase`, and each test module is a subclass of it, and calls the method `super.create_sync_global_repo()` which will create its own "global" repository of the module.

**Comment by Ichimonji10** [comment]
> (1) Module call approach: this has already been tried with [this branch](https://github.com/PulpQE/pulp-smash/compare/master...danuzclaudes:2.9-issue-setupmodule).

This approach is feasible, just not with the specific approach listed in that branch. In that branch, repositories are created and synced in `setUpModule()` functions and destroyed in `tearDownModule()` functions. That's totally OK; what's problematic is to store these module-wide repository IDs in `pulp_smash/tests/rpm/cli/utils.py`. What happens if two different modules are executed in parallel? Two different `setUpModule()` functions will write their repository ID to `pulp_smash.tests.rpm.cli.utils.REPO_ID`, and one of the values will be overwritten & lost.

A more work-able approach is to store the repository ID referenced by `setUpModule()` and `tearDownModule()` in the module, alongside the functions. For example, `pulp_smash.tests.rpm.cli.utils.test_foo.setUpModule()` might write to `pulp_smash.tests.rpm.cli.utils.test_foo._REPO_ID`, and `pulp_smash.tests.rpm.cli.utils.test_bar.setUpModule()` might write to `pulp_smash.tests.rpm.cli.utils.test_bar._REPO_ID`. This approach allows for a single repository to be shared by an entire module.

This still isn't ideal, as we've now restricted ourselves to parallelising tests at the per-module level. Tests can't be parallelised at the per-test-case level. :( But it at least allows some modules to sync less data.

> (2) Inheritance approach:
>
> Create a `rpm.cli.BaseTestCase`; each test module is a subclass of it, and each calls the method `super.create_sync_global_repo()` which will create its own "global" repository of the module. Please let me know which is the better option here.

Classes can use inheritance. Modules can not.

----

If your intent is to make Pulp Smash more efficient, so that it syncs less data, what you're really asking for is for the unittest framework itself to create fixtures at some level higher than the class level. unittest offers [class and module fixtures](https://docs.python.org/3.5/library/unittest.html#class-and-module-fixtures); unittest does not offer package fixtures. It may be possible to shoe-horn in package-level fixtures by creating a module such as `pulp_smash.tests.rpm.cli.test_fixtures`, which would create and sync a repository.

Before going down this route, though, it's worth asking:

* Will this cause issues with future development work? (Possibly. Test case parallelisation doesn't play well with module-wide or package-wide fixtures.)
* Is this the best way to make the test suite execute faster? (We don't know. We need to add coverage reports to find out what our test suite is even spending time doing.)
* Is this the most important goal for us right now? (No. We need to port RCM tests. We need coverage reports on Pulp; we need to test Pulp & Satellite together; we need to port RCM tests; etc.)

**Comment by danuzclaudes** [comment]
@Ichimonji10: Thank you for you detailed tutorials on it. And I agree that it is not the PulpQE's focus. I'll close this discussion then.
