### ISSUE TITLE
Test if a full re-sync can be forced (force_full importer option)

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#339]
https://pulp.plan.io/issues/1982

Setting or overriding force_full option on a Importer will cause a full re-sync to be performed. Check if that  can be done by:
- Setting it to true
- Setting it to false
- Omitting it

The last two items a full re-sync must not happen.

The force_full importer option was added on Pulp 2.10, the test should make sure to just run when testing a Pulp 2.10 system.

**Comment by dralley** [comment]
@elyezer Just to clarify re: "The last two items a full re-sync must not happen."

There are a number of conditions that should trigger a full resync - the force_full flag is only one of them.  For instance, if there is no previous sync, if the configuration has changed since the last sync, if content has been removed since the last sync, etc.  If any of those conditions are true a sync will (and should be) forced.

**Comment by elyezer** [comment]
@dralley thanks for the clarification.

**Comment by dralley** [comment]
@elyezer  No problem!  Also that's not an exhaustive list - there are a few others and some may vary by plugin.
