### ISSUE TITLE
Repos can be created and synced successfully with mirrorlist feed

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#384]
Test that repos can be created and synced with mirrorlist --feed
https://pulp.plan.io/issues/2224
https://pulp.plan.io/issues/175

1. pulp-admin -vv rpm repo create --repo-id mirror --feed "http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os"  --relative-url mirror

2. pulp-admin rpm repo sync run --repo-id=mirror

Assert that

1. Repo create is successful with the --relative-url 
2. Repo create is successful without --relative-url
3. Repo can be synced with relative-url
4. Repo can be synced without relative-url
5. Repo can be published with relative-url
7. Repo can be synced with lazy settings (on_demand,background)

**Comment by Ichimonji10** [comment]
The given set of commands in this test case will sync a significant number of packages. For example, the command above will resolve to a page like http://mirror.fusioncloud.co/pub/centos/7.2.1511/os/x86_64/Packages/, which lists over 9,000 packages. It's unacceptable for an automated test to sync that many packages, especially from systems not hosted by us.

I'm not aware of any good technique for choosing which packages should be synced from a repository. The [yum importer documentation](http://docs.pulpproject.org/plugins/pulp_rpm/tech-reference/yum-plugins.html#yum-importer) does list a `skip` option, but:

* `skip` is a blacklisting tool. Should the set of content types change or be expanded, we'd unknowingly start syncing additional content. A whitelisting tool is needed.
* `skip` is a coarse tool. It lets one select certain types of packages, like RPMs and SRPMs, but not individual packages.

I don't think this bug is suitable for automated testing, given Pulp's current capabilities.

**Comment by omaciel** [comment]
@Ichimonji10 @preethit is it possible to further filter the provided `feed`? If not, can we generate our own fixture that would allow us to automate this? I don't think that this issue should be closed but further developed so that the use case can be automated imho.

**Comment by mhrivnak** [comment]
Like @omaciel I also had the thought that we should have a fixture that provides a simple mirror list of a small repo.

**Comment by Ichimonji10** [comment]
> can we generate our own fixture that would allow us to automate this?

The mirrorlist files hosted by centos contain full URLs including hostnames. If we want to do something similar, Pulp Fixtures can't generate that mirrorlist, as it's unaware of where files are being hosted.

The Jenkins job that generates fixtures and copies said files to https://repos.fedorapeople.org may also be able to create a mirrorlist file, where said mirrorlist contains a single entry pointing to https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm/ (i.e. `urljoin(base_url, 'rpm')`).

**Comment by Ichimonji10** [comment]
@mhrivnak Can mirrorlist files contain relative URLs?

**Comment by mhrivnak** [comment]
I'm not sure if that's possible, but I think it would be very unusual, so I would not recommend using relative paths as a primary test case for mirror lists. Maybe for edge-case testing.

Mirror lists provide value by spreading load across multiple hosts and networks, and by providing redundancy in case a particular host is unreachable. Using relative paths in a mirror list removes both of those benefits, so I'm not sure what you'd be left with. I've never seen a mirror list with anything but full URLs.

**Comment by Ichimonji10** [comment]
> Mirror lists provide value by spreading load across multiple hosts and networks, and by providing redundancy in case a particular host is unreachable. Using relative paths in a mirror list removes both of those benefits, so I'm not sure what you'd be left with.

I understand that such an approach isn't typical. The benefit I'm weighing is that, should relative URLs be legal, the mirrorlist could be generated right in Pulp Fixtures. However, it seems that we can't generate the mirrorlist in Pulp Fixtures, given our desire to include absolute URLs. That means looking at e.g. Jenkins.

**Comment by elyezer** [comment]
Since the jenkins job knows the full URL maybe it can generate the mirror list using `make fixtures/mirrorlist` or something similar that may accept an argument providing the prefix for the relative path to generate the URLs.

**Comment by Ichimonji10** [comment]
We may want to make two or three mirrorlist files: one that contains only invalid entries, one that contains a mixture of invalid and valid entries, and possibly one with only valid entries. There's at least two types of invalid entries: a URL that, when fetched, returns an HTTP 404; and a URL that is valid, but for which there is no `$url/repodata/` directory.
