### ISSUE TITLE
publish step error handling incorrectly assumes open file

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#479]
Please see more info [here](https://pulp.plan.io/issues/2136)

**NOTE**: This may require the creation of a special repository (fixture)!

**Comment by mhrivnak** [comment]
This would be very difficult to test. You would have to sabotage the filesystem during the publish. It might not even be possible to do reliably.

You can see my thoughts here on how unlikely this bug is to be hit at all: https://bugzilla.redhat.com/show_bug.cgi?id=1327522#c7

I recommend investing automation energy elsewhere.

**Comment by elyezer** [comment]
@mhrivnak thank you for the information. With that said I will close this issue.
