### ISSUE TITLE
iso importer fails without useful error message

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#482]
Please see more info [here](https://pulp.plan.io/issues/2006)

This is blocked by #481

**Comment by dkliban** [comment]
ISO importer used to give a vague error message when one or more ISOs in a repository could not be downloaded. So a good test for this would be to:

1. create an ISO repository in Pulp. 
2. Upload to the repository some files that will be used as fixtures in  the test.
3. Publish the ISO repository. 
4. Add the content of the published repository to github as a fixture for the test.
5. Remove one of the files (but not all files).
6. Use the new fixture repository (with a missing content unit) to test. 
7. Write a test that syncs this repository and make sure that the error message reported by the API says that the failure occurred due to a 404 for that particular file that is present in PULP_MANIFEST but not available to download.

**Comment by Ichimonji10** [comment]
> 5. Remove one of the files (but not all files).

Where should a file be removed from? From the ISO file?

**Comment by dkliban** [comment]
The ISO distributor should be called the File distributor. ISO units can be any type of file. When the ISO distributor publishes repositories, it publishes all the units in the repository and PULP_MANIFEST file which lists all the files in the repository. 

In step 4, the published ISO repository should be committed to a github repository that is used for fixtures.  

In step 5, one of the published files in the new fixtures directory should be removed. As a result the PULP_MANIFEST will still contain the missing file, but the file will not be available for download.
