### ISSUE TITLE
Failure count and does not match count of 'F' characters in test runner output

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#51]
I am running pulp smash at commit d1dbb1c33601199fd9ab61e1a23c3b35e8132cab

When I run pulp-smash against Pulp master I see the following output:

```
....F...s.s.......ssss..............................................................s........
<snip test failure details whic are correct>
FAILED (failures=5, skipped=7)
```

I expected the output from the test runner to show seven 'F' characters, but instead only 1 is shown.

**Comment by Ichimonji10** [comment]
Each `.`, `s`, `F` and so on corresponds to one test method. Each test method can have multiple skips, errors, failures and so on due to sub-tests. This is an issue with various test runner GUIs, if anything. See: https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests
