### ISSUE TITLE
Ensure worker heartbeat debug statement only show UTC time

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#513]
Test plan for [Issue 2516](https://pulp.plan.io/issues/2516)

## Verify that the log statement shows only UTC time

1. Start with a health 2.13+ Pulp system
2. Stop all processes
3. Set logging level to DEBUG in server.conf
4. Start all Pulp services
5. Wait 7 seconds after services are all started
6. Verify in the logs each process logs a heartbeat at DEBUG level
7. Verify that each log statement contains the worker name
8. Verify that each log statement contains 1 timestamp in the log statement and that it contains the correct UTC time

**Comment by Ichimonji10** [comment]
We're going to manually verify this issue after it enters the MODIFIED state. We think this is appropriate because:

* The system logs are filled with human-readable prose, making automated tests very fragile.
* We think that this test may require a lot of work, and other tests may be written more quickly.
