### ISSUE TITLE
Test schema version 2 manifests published by pulp docker

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#555]
[Install docker](https://docs.docker.com/engine/installation/). Get docker v2 content. Deploy registry on localhost by following example [here](https://docs.docker.com/registry/deploying/). Go as far as pushing the ubuntu image into the registry.

Create a docker v2 repo that will sync from local registry created earlier:

```bash
pulp-admin docker repo create \
  --feed http://127.0.0.1:5000 \
  --upstream-name ubuntu \
  --repo-id mydocker2 \
  --auto-publish false
```

Sync v2 content from the local registry: `pulp-admin docker repo sync run --repo-id mydocker2`

Clone crane: `git clone git@github.com:/pulp/crane`

Add the following /etc/crane.conf:

```ini
[general]
debug: true
data_dir: /var/lib/pulp/published/docker/v2/app/
endpoint: localhost:5001
```

Sync mydocker2 repo from the local registry: `pulp-admin docker repo sync run --repo-id mydocker2`

Publish mydocker2 repository: `pulp-admin docker repo publish run --repo-id mydocker2`

[Configure crane](https://github.com/pulp/crane/blob/master/docs/index.rst#deployment). It should run  using apache and mod_wsgi.

Docker pull from crane: `sudo docker pull localhost:5001/mydocker2`

Verify that pulling from crane returns a schema version 2 manifest. Grep through `/var/log/httpd/ssl_access_log`. The path accessed during pull should include:

```
<repo id>/manifests/2/latest 127.0.0.1 - - [12/Feb/2017:22:03:24 +0000] "GET /pulp/docker/v2/mydocker2/manifests/2/latest HTTP/1.1" 200 1357
```

**Comment by ipanova** [comment]
Install newer docker client 1.9 and newer.

with already synced repo from some registry into pulp, and published it, so crane is serving it, do:

*PULL BY TAG*

1. docker pull manifest by tag( where you would choose a tag that references schema 2 version)
2. check in httpd access log the path, which tells you that manifest schema 2 was returned

1. docker pull manifest by tag( where you would choose a tag that references *just* schema 1 version)
2. check in httpd access log the path, which tells you that manifest schema 1 was returned

1. docker pull manifest by invalid tag
2. confirm that 404 is returned

*PULL BY DIGEST*

1. docker pull manifest by digest( which would identify schema 2 version)
2. check the response headers content-type returned( it should be schema 2 mediatype). Or check the manifest itself, specifically its schema version. Up to you how you do it, just ensure that schema 2 is returned.

1. docker pull manifest by digest( which would identify schema 1 version)
2. Same as above. Check the manifest itself, specifically its schema version. Ensure that schema 1 is returned.

1. docker pull manifest by invalid digest
2. ensure 404 is returned

*Note*
1. to figure out which tags reference which manifest schema versions, check the crane metadata json file( i.e redirect file)




Install older docker client 1.8 and older:

with already synced repo from some registry into pulp, and published it, so crane is serving it, do:

*PULL BY TAG*

1. docker pull manifest by tag( where you would choose a tag that references schema 2 version)
2. check in httpd access log the path, which tells you that manifest schema 1 was returned

1. docker pull manifest by tag( where you would choose a tag that references *just* schema 1 version)
2. check in httpd access log the path, which tells you that manifest schema 1 was returned

1. docker pull manifest by invalid tag
2. confirm that 404 is returned

*PULL BY DIGEST*

1. docker pull manifest by digest( which would identify schema 2 version)
2. You will hit a compatibility issue, widely known in docker. Pulp does not need to do/solve here at this point. https://docs.docker.com/registry/compatibility/#/registry-v23

1. docker pull manifest by digest( which would identify schema 1 version)
2. Check the manifest itself, specifically its schema version. Ensure that schema 1 is returned.

1. docker pull manifest by invalid digest
2. ensure 404 is returned

**Comment by ipanova** [comment]
https://etherpad.net/p/schema2-testing

**Comment by ipanova** [comment]
Upgrade scenario:
https://github.com/pulp/pulp_docker/pull/187#issuecomment-283995647

**Comment by ipanova** [comment]
There will be more detailed docs on how to configure crane once this task is complete https://pulp.plan.io/issues/2608

**Comment by elyezer** [comment]
We may consider using Docker in Docker [1], with that we can check the behavior on multiple docker versions within a single System's Docker installation.

[1] https://hub.docker.com/_/docker/

**Comment by Ichimonji10** [comment]
I can't test this issue at this time. There's a lack of documentation. I've started by filing an issue here: https://pulp.plan.io/issues/2665

More on Monday.

**Comment by Ichimonji10** [comment]
Over the past week or so, I've basically figured out that all of our API-based Docker tests are fragile and need to be re-written. The problem is the pulp_docker plugin isn't intended to be used directly by end users. The pulp_docker API endpoints are subject to breaking changes, and as pointed out in my previous comment, there's room for expanded documentation. The solution is for end users to use Crane instead.

I think the next step toward testing this issue is to update pulp_packaging so that Crane can be installed in an automated fashion.

**Comment by Ichimonji10** [comment]
Over the past several weeks, I've gotten up to speed with pulp_docker and especially Crane. I've whipped up a pull request which adds a Crane role to our Ansible playbooks in [Pulp Packaging #346](https://github.com/pulp/pulp_packaging/pull/346), and I've re-written some of our tests to use Crane in [Pulp Smash #624](https://github.com/PulpQE/pulp-smash/pull/624). Yay!

Those changes are currently blocked by [Pulp #2719](https://pulp.plan.io/issues/2719). As soon as it's fixed, we can have our automated jobs start installing and using Crane. That doesn't help us with the 2.13 beta, though. In the mean time, I'm manually getting Crane running on our 2.13 beta systems, which will at least let me test this issue.

I was hoping to finish up with 2.13 beta testing today, but unfortunately, I can't provision any such VMs:

> According to multiple reports on Twitter, the Fedora Infrastructure Status page, and the #fedora-admin Freenode IRC channel, Red Hat is suffering a massive network outage at their primary data center.
>
> Details are sketchy at this point, but it looks to be impacting the Red Hat Customer Portal; as well as all their repositories (including Fedora, EPEL, Copr); their public build system, Koji; and a whole host of other popular services. 

You can see the flames at http://status.redhat.com/ and http://status.fedoraproject.org/. I'm going to have to kick back final testing until Monday.

**Comment by Ichimonji10** [comment]
Red Hat and Fedora's services are back up and running. I verified the following issues:

* https://pulp.plan.io/issues/2099
* https://pulp.plan.io/issues/2336

I verified these issues on a Fedora 24 system with the 2.13 beta installed by doing the following:

1. Create a Docker repository with a (v2) feed of https://registry-1.docker.io.
2. Sync the library/busybox image.
3. Publish the repository.
4. Run `docker pull localhost:5000/repo-name`.
5. Execute `docker run localhost:5000/repo-name echo foo` and `docker run image-checksum echo foo`.

This test is basic, but it at least verifies that Docker repositories can manage v2 content. Also, for the record:

```console
$ docker --version
Docker version 1.10.3, build e03ddb8/1.10.3
```

I executed an abbreviated version of the above on Fedora 25 and RHEL 7 with the 2.13 beta. I couldn't execute complete tests on those distributions due to an error with `docker-storage-setup.service`. Oh, and I ran the tests in [Pulp Smash #624](https://github.com/PulpQE/pulp-smash/pull/624) against all three systems. The results were as expected.

**Comment by Ichimonji10** [comment]
I've taken the unusual step of rescinding my "verified" stamps of approval on:

* https://pulp.plan.io/issues/2099
* https://pulp.plan.io/issues/2336

I've realized that I know less about Docker than I thought I knew. The problem is that, while I can sync content from registry-1.docker.io, and while I can `docker pull localhost:5000/repo-name`, I don't know  the manifest version (schema version) of the images downloaded by Pulp, nor do I know the manifest version (schema version) of the images that Docker downloads.

The very first comment in this thread suggests the following:

> Install docker. Get docker v2 content. Deploy registry on localhost by following example here. Go as far as pushing the ubuntu image into the registry.

However, I don't know how to get Docker v2 content specifically. How do I know that I'm getting v2 instead of v1 content?

[This comment](https://github.com/pulp/pulp_docker/pull/187#issuecomment-283995647) almost answers my questions:

> 5. perform docker pull localhost:5000/alpine:latest. Docker pull should work. Make a curl request to crane API ensure schema2 is returned
> 6. perform docker pull localhost:5000/busybox:latest. Docker pull should work. Make a curl request to crane API ensure schema1 is returned

However, I don't know what curl commands should be executed.

**Comment by ipanova** [comment]
To answer your question about 'How can i figure out if i am getting v1 content or v2 content, and in case i get v2 content which schema version i got pulled'

There are specs for each version. 

this is how v1 content looks like https://github.com/moby/moby/blob/master/image/spec/v1.md#image-json-description

With regards to v2 content, there was introduced a concept of mediatype which basically tells you manifest schema1 or schema2 you pulled( omitting the manifest list for now, since we dot support that yet)

v2 schema1 version https://docs.docker.com/registry/spec/manifest-v2-1/
v2 schema2 version https://docs.docker.com/registry/spec/manifest-v2-2/

To make a curl request to crane API you need to simulate docker client's behaviour( because as you pointed out when you do `docker pull` you don not know what you pulled)

It is important what kind of docker client you have, based on this you curl request will be different.

For example older docker clients to not set anything in the accept headers, newer ones, set the mediatype they accept( i.e. manifest list, schemav2 and schemav1)

```
$ curl -L -H "Accept: application/vnd.docker.distribution.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json" -k -X GET 'http://localhost:1234/v2/foo/manifests/latest'
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1465,
      "digest": "sha256:00f017a8c2a6e1fe2ffd05c281f27d069d2a99323a8cd514dd35f228ba26d2ff"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 677607,
         "digest": "sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3"
      }
   ]
```

**Comment by Ichimonji10** [comment]
Thanks, @ipanova. That contextual info along with the `curl` command was everything I needed. I can definitely assert that Pulp (and Crane) properly return v1 and v2 schemas when requested. Here's the prettified output of:

* `curl --location http://localhost:5000/v2/myrepo/manifests/latest`
* `curl --location -H accept:application/json http://localhost:5000/v2/myrepo/manifests/latest`
* `curl --location -H accept:application/vnd.docker.distribution.manifest.v1+json http://localhost:5000/v2/myrepo/manifests/latest`

```json
{
   "schemaVersion": 1,
   "name": "library/busybox",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"1295ff10ed92\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"Image\":\"sha256:0d7e86beb406ca2ff3418fa5db5e25dd6f60fe7265d68a9a141a2aed005b1ae7\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"container\":\"d12e9fb4928df60ac71b4b47d56b9b6aec383cccceb3b9275029959403ab4f73\",\"container_config\":{\"Hostname\":\"1295ff10ed92\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"Image\":\"sha256:0d7e86beb406ca2ff3418fa5db5e25dd6f60fe7265d68a9a141a2aed005b1ae7\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2017-03-09T18:28:04.586987216Z\",\"docker_version\":\"1.12.6\",\"id\":\"d7f9d170aa714bf287eb994aada10a57f4fb1bf8fd748cbfa36a7ab9549190c1\",\"os\":\"linux\",\"parent\":\"d0fb090f7b4758531261295c34b956bc0b8a6663fb98605612d3eb47a02cd7f5\",\"throwaway\":true}"
      },
      {
         "v1Compatibility": "{\"id\":\"d0fb090f7b4758531261295c34b956bc0b8a6663fb98605612d3eb47a02cd7f5\",\"created\":\"2017-03-09T18:28:03.975884948Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:c9ecd8ff00c653fb652ad5a0a9215e1f467f0cd9933653b8a2e5e475b68597ab in / \"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "JVS5:FLHE:WVYV:CCSG:KI7Y:JKMC:ZS7Z:JBI7:RX7D:T5UV:UIWN:6FNT",
               "kty": "EC",
               "x": "lBvzgDNIkULNiuDkt8JwYZgCWyRigo35yujUi-XlhpI",
               "y": "-NNlPrHpudJ8K6ukaQMfwPbkgnxcwJTVd1xNbNHLBXs"
            },
            "alg": "ES256"
         },
         "signature": "0rX8U46LDBd576Li7nZluxqH9MMPS5o-YPUUa_bhoEVRuUXVfglez8VyhvI62rNq7DRBqvJn0D2QTXFV74dvoQ",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjIwOTYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNy0wNC0yNlQxNToxODozM1oifQ"
      }
   ]
}
```

And here's the output of `curl --location -H accept:application/vnd.docker.distribution.manifest.v2+json http://localhost:5000/v2/myrepo/manifests/latest`:

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1465,
      "digest": "sha256:00f017a8c2a6e1fe2ffd05c281f27d069d2a99323a8cd514dd35f228ba26d2ff"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 677607,
         "digest": "sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3"
      }
   ]
}
```

The output is exactly as described by https://docs.docker.com/registry/spec/manifest-v2-1/ and https://docs.docker.com/registry/spec/manifest-v2-2/.

**Comment by Ichimonji10** [comment]
I just wrote some automated tests to validate the contents of the v2 image manifests as returned by pulp & crane. They make use of schemas like the following, which I find pretty kick-ass:

```python
IMAGE_MANIFEST_V2_SCHEMA_2 = {
    '$schema': 'http://json-schema.org/schema#',
    'title': 'Image Manifest Version 2, Schema 2',
    'description': (
        'Derived from: https://docs.docker.com/registry/spec/manifest-v2-2/'
    ),
    'type': 'object',
    'properties': {
        'config': {
            'type': 'object',
            'properties': {
                'digest': {'type': 'string'},
                'mediaType': {'type': 'string'},
                'size': {'type': 'integer'},
            },
        },
        'layers': {
            'type': 'array',
            'items': {
                'type': 'object',
                'properties': {
                    'digest': {'type': 'string'},
                    'mediaType': {'type': 'string'},
                    'size': {'type': 'integer'},
                    'urls': {
                        'type': 'array',
                        'items': {'type': 'string'},
                    },
                },
            },
        },
        'mediaType': {'type': 'string'},
        'schemaVersion': {'type': 'integer'},
    },
}
```
