### ISSUE TITLE
Add ability to set threshold on task polling

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#62]
Currently some tests fail intermittently because Pulp is taking too long to perform a task. Test writer should be able to use a default threshold or define a custom one for duration of a particular task.

**Comment by Ichimonji10** [comment]
Which tests periodically fail, and on which lines of code? What are the other characteristics of the failures? (If a task goes indefinitely, then what causes a Pulp Smash to fail?)

**Comment by Ichimonji10** [comment]
The failures @dkliban describes are pretty catastrophic and universal. It's not as if two or five tests will intermittently fail in each test run. Instead, on some test runs, every polled task (or at least most polled tasks) will fail to complete. As a result, you'll see results like "37 failed tests". It's unclear whether we get catastrophic test failures because of errors somewhere (in Pulp, or the system hosting it, or...), or simply because the systems under test are slow.

Currently, Pulp Smash is set to poll each individual task for up to 50 seconds. The actual wait time is longer than that, as time spent waiting for Pulp to respond to each `GET /pulp/api/v2/tasks/.../` request is not counted. (The polling function is simple, but pretty stupid.)

**Comment by Ichimonji10** [comment]
I've made the inelegant but pragmatic change of bumping the task poll period from 50+ seconds to 120+ seconds. It's unclear whether this has had any effect. Our RHEL 6 system produced normal test results, but our Fedora 23 system has produced another catastrphic time-out failure.

**Comment by Ichimonji10** [comment]
Since this issue was filed, I've only seen tests fail due to time-outs once: when Pulp services legitimately broke and were failing to function.

We can further increase the timeout window if need be. However, I'm wary of doing so: there's little difference between an unresponsive service and a dead service, and if it takes more than two minutes for Pulp to perform an action, I'm inclined to call that a bug. If we really do need to increase the timeout window, I'd like to also make sure to improve the time-out mechanism in Pulp Smash itself. Right now, Pulp Smash waits 120s *in addition to* whatever time is consumed communicating with the Pulp server. It'd be better if the time-out mechanism is asynchronous and interrupts whatever Pulp Smash is doing. In other words, this code is naive and should be improved if we want to also increase the timout:

```python
    while True:
        response = requests.get(
            urljoin(server_config.base_url, href),
            **server_config.get_requests_kwargs()
        )

        # [SNIP]

        # This approach is dumb, in that we don't account for time spent
        # waiting for the Pulp server to respond to us.
        sleep(5)
```
