### ISSUE TITLE
pulp-smash should only run tests for plugins that are actually installed

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#84]
Pulp smash should inspect the system under test to determine which plugins are installed. Based on that information some or all tests should be run.

**Comment by Ichimonji10** [comment]
:+1:

What do you think is a good, canonical way of determining which plugins are installed? I of course like the idea of checking with a package manager. But when installing using the scripts shipped with Pulp, which is what happens when one executes `vagrant up`, the package manager may be left ignorant of that. Can you shed some light on the interactions between the package manager and the installation scripts, @dkliban?

**Comment by omaciel** [comment]
Robotello uses a `skip_if_not_set` (or something similar) that will skip a test or tests if certain configurations are not available. For example, if there's no Docker installed locally, then docker related test are skipped.

I'm in favor of making tests as smart as possible, but let's be careful not to make them too smart :)  Folks will only look at test results if something goes wrong and if we skip tests without some type of vigilance, we run the risk of ignoring the testing of certain areas.

**Comment by Ichimonji10** [comment]
The Pulp Smash code is organized in such a way that it's easy to select which plugins you'd like to test. Can we tell the test runner to blacklist certain packages (I mean a "package" in the Pythonic sense, not the package manager sense) during test discovery?

**Comment by Ichimonji10** [comment]
@asmacdo or anyone else: is there some good, canonical way to determine whether a given plugin is installed? One option is to execute `test -d /path/to/plugin/dir` on the host. That's ugly and relies heavily on implementation-specific details, but it works. Another option is to ask pulp-admin on the target system, though that brings up its own set of possible bugs. Thoughts? See: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:ostree

**Comment by Ichimonji10** [comment]
Is there, say, an API call I can make where I ask Pulp which plugins are installed and it responds with a list of them?

Pulp is only available through its API. Even the pulp-admin CLI client talks to Pulp via its API. And this is appropriate: it means that the target host can install Pulp however it likes (system-wide, per-use, in a virtualenv, etc), and client don't have to care. If we can maintain that level of abstraction, it could be nice.

Of course, our [`pulp_smash.utils.reset_pulp`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.utils.html#pulp_smash.utils.reset_pulp) function already makes assumptions about where files are on disk, so we are already making some assumptions about where files exist. Still, it'd be nice to stick as close as possible to that level of abstraction.

**Comment by Ichimonji10** [comment]
A nice solution to this issue has been implemented in #96. However, the solution only works on Pulp 2.7. This is because, as described in [Pulp issue 1642](https://pulp.plan.io/issues/1642), the list of content unit types returned by Pulp 2.8 is incomplete. Examples of "content unit types" are `docker_image`, `python_package` and `ostree`.

**Comment by Ichimonji10** [comment]
I have a strong interest in pursuing this further, but it's not at the top of my priority list. Unassigning myself.

**Comment by Ichimonji10** [comment]
[Pulp issue 1642](https://pulp.plan.io/issues/1642) is fixed in the current Pulp 2.8 release. It's reliable enough that, as of c9825e545993d871413b83bf88728cd6df05eff8, we now depend on Pulp to correctly report which plugins are installed. Closing.
